name: BasicMazeWorldGenerator
main: world.anhgelus.msmp.basicmazeworldgenerator.BasicMazeWorldGenerator
api-version: 1.19
author: ["MSMP", "Anhgelus Morhtuuzh"]
version: '${version}'
worlds:
  world:
    generator: BasicMazeWorldGenerator
depend:
  - MSMPCore
  - kotlin-stdlib
load: STARTUP
